stages:
  - install
  - lint
  - build
  - deploy

default:
  image: node:20
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/

variables:
  MONGODB_URI: "mongodb://mongo:27017"
  MONGODB_DB: "reparto_test"

install:
  stage: install
  script:
    - npm ci
  artifacts: {}

lint:
  stage: lint
  script:
    - npx eslint . --ext .js,.jsx,.ts,.tsx
  allow_failure: true

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - .next/
    expire_in: 1 week

deploy:
  stage: deploy
  script:
    - echo 'TODO deployment steps'
  environment:
    name: production
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: never
